### PR TITLE
Weatherflow API bug workaround

### PR DESCRIPTION
**Pull request by mr-manuel**
A bug caused the weather type to be 0, which caused other problems.

### CODE REVIEW

**Comment by mschlenstedt** [comment]
Hi,

so the bug was "cc-" in the API reply? What about the changes to the Weather code (formerly 15, now 18 for example)? Did we use the wrong codes in the past?

**Comment by mschlenstedt** [comment]
Ah, just read your comment here: https://github.com/mschlenstedt/LoxBerry-Plugin-Weather4Lox/issues/71

I understand ;-)

Fixed with #75

**Comment by mschlenstedt** [comment]
I will add another weather service (hopefully this weekend) and then release a new version with your changes. Thanks!

**Comment by mr-manuel** [comment]
Sorry, my initial pull request were only the first two changes, therefore the description. The other changes where made after the pull request, so I don‘t know how they landed here. Thanks

**Comment by mschlenstedt** [comment]
Yes, GitHub takes over all changes in your fork - rgardless when you made the PullRequest.

But if I understand correctly the changes to the weather code fix the problems in this issue https://github.com/mschlenstedt/LoxBerry-Plugin-Weather4Lox/issues/71

So I can also include them in the next release, correct?

**Comment by mr-manuel** [comment]
Yes and yes.

**Pull request merged**
