### PR TITLE
Add support for Weatherflow stations

### PR DESCRIPTION
**Pull request by nufke**
Support for Weatherflow smart weather stations (e.g. Tempest). Early adopters (including myself) purchased the new Tempest Weather System via crowdfunding sites Kickstarter or Indiegogo and the first weather stations have been delivered to Europe in November 2020. Data can be retrieved via UDP or via web based REST API. Users can obtain a personal API key for their station, to read current observation data as well as forecast data.

This pull request adds Weatherflow support to the Weather4Lox plugin using the REST API. Code is running in my environment (Loxberry v2.2.0.3, Weather4Lox v4.8.0.2) for a couple of days now without problems.
NOTE: Although the forecast API is working, the public documentation of Weatherflow is still to be announced soon, so I expect some (minor) changes and will incorporate these along the way.

Would appreciate feedback if this pull request contains all necessary changes to be incorporated in the plugin.

### CODE REVIEW

**Comment by mschlenstedt** [comment]
Thanks a lot! Can you provide me an API Key so that I can test your commit? Michael (AT ) loxberry.de

**Comment by nufke** [comment]
Question related to the mapping to the Loxone weathercodes and icons. It seems that code Loxone weathercode 19, 20, 21 (stark bewölkt) is not used in the icon mapping. It seems the Weatherflow "Cloudy" icon maps to internal weathercode=4 which again maps to Loxone weathercode 9 (wolkig), but the icon still shows a half sun, so everyone things it is partly cloudy. Instead I would expect "Cloudy" should map to Loxone "stark bewölkt". But changing the file datatoloxone.pl would also affect the other weather mappings. Please advice how to proceed.

Improving this mapping might not solve the complete issue. I noticed in the Loxone interface that even for "stark bewölkt" the icon shows a part of the sun, so relates to ~80% coverage, not 100%. So the Loxone icon for "stark bewölkt" seems wrong. When exploring the webinterface, I noticed these are svg graphics which seems not stored on the miniserver. So not sure if we can overrule the weather icons with our own. 

Any experience related to this would be appreciated.

**Comment by nufke** [comment]
Weatherflow has published their API here: https://weatherflow.github.io/Tempest/api/swagger/
Since the API changes were minimal, the initial grabber did still work. The latest commit eeac3d9 is is clean-up of the Weatherflow grabber and compliant with this Weatherflow API.

**Comment by mschlenstedt** [comment]
Thanks for this great commit!

**Pull request merged**
